# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 074a042fb01a9a30e5469badeda6088c495622f0b40ac3b14dc1b5f91a60f65ab90050e48363a39a96fdfc9809a2a0d109338a225dc2e9de868deb278ed6ac34

test:
  secret_key_base: 205926252bd0fc10e4ea516ab4dbaba8d3716c4dde764f67df0e2835fe051b17e0cc28b5dfa614f216300552b56fa9499f461140fafb7d2915f52249b7ce9c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
